//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ActD.rc
//
#define ID_THREE                        0
#define IDC_LOADNAMES                   3
#define IDD_ABOUTBOX                    100
#define IDD_DIALOGBAR                   103
#define IDR_MAINFRAME                   128
#define IDR_TB1                         201
#define IDD_BIPOLDLG                    203
#define IDD_MAPDLG                      205
#define IDD_HARDDLG                     206
#define IDD_DLGVIEW                     207
#define IDD_COLORSDLG                   208
#define IDB_ARROWIN                     209
#define IDB_ARROWOUT                    211
#define IDI_OSC                         212
#define IDB_SAVE                        213
#define IDI_SNAP                        213
#define IDB_LOAD                        214
#define IDB_TOOL                        215
#define IDD_VIEWSETDLG                  216
#define IDD_TRIGVIEWDLG                 217
#define IDD_PROGSET                     218
#define IDD_ACQTRIGDLG                  219
#define IDD_OFFSETPAGE                  220
#define IDD_OSCDLG                      221
#define IDD_SNAPDLG                     222
#define IDD_INFOPANEL                   223
#define IDD_FINFOPANEL                  224
#define IDD_HDRDLG                      225
#define IDD_LISTPANEL                   226
#define IDB_UNLOCK                      226
#define IDB_LOCK                        227
#define IDC_FRAME                       1000
#define IDC_FRAME2                      1001
#define IDC_MODN                        1001
#define IDC_NMODS                       1002
#define IDC_TOUCH                       1003
#define IDC_NCH                         1005
#define IDC_REFTXT                      1006
#define IDC_TCH                         1007
#define IDC_DISPTXT                     1007
#define IDC_CLOSE                       1008
#define IDC_TRIGGER                     1009
#define IDC_BIPOLAR                     1010
#define IDC_BPLIST                      1011
#define IDC_NAME                        1016
#define IDC_TIMER                       1016
#define IDC_NUMCOL                      1016
#define IDC_MV1                         1016
#define IDC_FRAMELEN                    1016
#define IDC_REMOVE                      1017
#define IDC_MV2                         1017
#define IDC_SNAME                       1018
#define IDC_MV3                         1018
#define IDC_MODE                        1019
#define IDC_MV4                         1019
#define IDC_LENGTH                      1020
#define IDC_SLENGTH                     1021
#define IDC_FILTERS                     1025
#define IDC_SCALE                       1027
#define IDC_SSCALE                      1028
#define IDC_SNUMCOL                     1028
#define IDC_SCALEUNIT                   1029
#define IDC_BPSCALE                     1030
#define IDC_SBPSCALE                    1031
#define IDC_SCROLL                      1032
#define IDC_ZERO                        1033
#define IDC_LOADDEF                     1033
#define IDC_TRFIRST                     1033
#define IDC_BROWSE                      1033
#define IDC_CMBFLP                      1034
#define IDC_SAVEDEF                     1034
#define IDC_CMBFHP                      1035
#define IDC_DECIMATE                    1035
#define IDC_SAVENOW                     1035
#define IDC_COLORS1                     1036
#define IDC_BPSCALEUNIT                 1036
#define IDC_COLORS2                     1037
#define IDC_TRNEXT                      1037
#define IDC_COLORSC                     1038
#define IDC_TRLAST                      1038
#define IDC_TRPREV                      1039
#define IDC_COLBG                       1039
#define IDC_COL1                        1040
#define IDC_COL2ODD                     1041
#define IDC_COL2EVEN                    1042
#define IDC_COLLIST                     1043
#define IDC_SEPARATOR                   1044
#define IDC_TRIGDEC                     1045
#define IDC_COLBGBP                     1045
#define IDC_BATTERY                     1047
#define IDC_CMS                         1048
#define IDC_S_LENGTH                    1048
#define IDC_POWER                       1049
#define IDC_BIPOLSEPCOLOR               1050
#define IDC_TOOL                        1051
#define IDC_LOCK                        1052
#define IDC_TIME                        1053
#define IDC_SAVEONCLOSE                 1054
#define IDC_TRCOL0                      1055
#define IDC_TRCOL1                      1056
#define IDC_TRCOL2                      1057
#define IDC_TRCOL3                      1058
#define IDC_TRCOL4                      1059
#define IDC_TRCOL5                      1060
#define IDC_TRCOL6                      1061
#define IDC_TRCOL7                      1062
#define IDC_TRCOL8                      1063
#define IDC_TRCOL9                      1064
#define IDC_TRCOL10                     1065
#define IDC_TRCOL11                     1066
#define IDC_TRCOL12                     1067
#define IDC_TRCOL13                     1068
#define IDC_TRCOL14                     1069
#define IDC_TRCOL15                     1070
#define IDC_LOW0                        1072
#define IDC_WINDEF                      1074
#define IDC_WININD                      1075
#define IDC_LOHI0                       1075
#define IDC_WINLOAD                     1076
#define IDC_LOHI1                       1076
#define IDC_PROGLOAD                    1077
#define IDC_LOHI2                       1077
#define IDC_PROGSAVE                    1078
#define IDC_LOHI3                       1078
#define IDC_LOHI4                       1079
#define IDC_OFCOL4                      1080
#define IDC_LOHI5                       1080
#define IDC_LOW1                        1081
#define IDC_LOHI6                       1081
#define IDC_OFCOLNODATA                 1081
#define IDC_LOW2                        1082
#define IDC_LOHI7                       1082
#define IDC_OFCOLANAVAIL                1082
#define IDC_LOW3                        1083
#define IDC_LOHI8                       1083
#define IDC_OFCOLOFF                    1083
#define IDC_LOW4                        1084
#define IDC_LOHI9                       1084
#define IDC_LOW5                        1085
#define IDC_LOHIA                       1085
#define IDC_LOW6                        1086
#define IDC_OFCOL3                      1086
#define IDC_LOHIB                       1086
#define IDC_LOW7                        1087
#define IDC_OFCOL1                      1087
#define IDC_LOHIC                       1087
#define IDC_LOW8                        1088
#define IDC_OFCOL0                      1088
#define IDC_LOHID                       1088
#define IDC_LOW9                        1089
#define IDC_OFCOL2                      1089
#define IDC_LOHIE                       1089
#define IDC_LOW10                       1090
#define IDC_LOHIF                       1090
#define IDC_LOW11                       1091
#define IDC_FREE                        1091
#define IDC_LOW12                       1092
#define IDC_GATED                       1092
#define IDC_LOW13                       1093
#define IDC_TRIGGERED                   1093
#define IDC_LOW14                       1094
#define IDC_HILO0                       1094
#define IDC_LOW15                       1095
#define IDC_HILO1                       1095
#define IDC_HILO2                       1096
#define IDC_HILO3                       1097
#define IDC_HILO4                       1098
#define IDC_HILO5                       1099
#define IDC_HILO6                       1100
#define IDC_HILO7                       1101
#define IDC_HILO8                       1102
#define IDC_HILO9                       1103
#define IDC_HILOA                       1104
#define IDC_HILOB                       1105
#define IDC_HILOC                       1106
#define IDC_HILOD                       1107
#define IDC_HILOE                       1108
#define IDC_HILOF                       1109
#define IDC_POSTTRIG                    1110
#define IDC_PRETRIG                     1111
#define IDC_TST0                        1112
#define IDC_TST1                        1113
#define IDC_TST2                        1114
#define IDC_TST3                        1115
#define IDC_TST4                        1116
#define IDC_TST5                        1117
#define IDC_TST6                        1118
#define IDC_TB0                         1119
#define IDC_TB1                         1120
#define IDC_TB2                         1121
#define IDC_TB3                         1122
#define IDC_TB4                         1123
#define IDC_TB5                         1124
#define IDC_TB6                         1125
#define IDC_TB7                         1126
#define IDC_TB8                         1127
#define IDC_TB9                         1128
#define IDC_TBA                         1129
#define IDC_TBB                         1130
#define IDC_TBC                         1131
#define IDC_TBD                         1132
#define IDC_TBE                         1133
#define IDC_TBF                         1134
#define IDC_AND1                        1135
#define IDC_HIA0                        1136
#define IDC_HIA1                        1137
#define IDC_HIA2                        1138
#define IDC_HIA3                        1139
#define IDC_HIA4                        1140
#define IDC_HIA5                        1141
#define IDC_HIA6                        1142
#define IDC_HIA7                        1143
#define IDC_HIA8                        1144
#define IDC_HIA9                        1145
#define IDC_HIAA                        1146
#define IDC_HIAB                        1147
#define IDC_HIAC                        1148
#define IDC_HIAD                        1149
#define IDC_HIAE                        1150
#define IDC_HIAF                        1151
#define IDC_ABF                         1152
#define IDC_ABE                         1153
#define IDC_ABD                         1154
#define IDC_ABC                         1155
#define IDC_ABB                         1156
#define IDC_ABA                         1157
#define IDC_AB9                         1158
#define IDC_AB8                         1159
#define IDC_AB7                         1160
#define IDC_AB6                         1161
#define IDC_AB5                         1162
#define IDC_AB0                         1163
#define IDC_AB1                         1164
#define IDC_AB2                         1165
#define IDC_AB3                         1166
#define IDC_AB4                         1167
#define IDC_LOA0                        1168
#define IDC_LOA1                        1169
#define IDC_LOA2                        1170
#define IDC_LOA3                        1171
#define IDC_LOA4                        1172
#define IDC_LOA5                        1173
#define IDC_LOA6                        1174
#define IDC_LOA7                        1175
#define IDC_LOA8                        1176
#define IDC_LOA9                        1177
#define IDC_LOAA                        1178
#define IDC_LOAB                        1179
#define IDC_LOAC                        1180
#define IDC_LOAD                        1181
#define IDC_LOAE                        1182
#define IDC_LOAF                        1183
#define IDC_TSA1                        1184
#define IDC_TSA2                        1185
#define IDC_TSA3                        1186
#define IDC_AND2                        1187
#define IDC_HIB0                        1188
#define IDC_HIB1                        1189
#define IDC_HIB2                        1190
#define IDC_HIB3                        1191
#define IDC_HIB4                        1192
#define IDC_HIB5                        1193
#define IDC_HIB6                        1194
#define IDC_HIB7                        1195
#define IDC_HIB8                        1196
#define IDC_HIB9                        1197
#define IDC_HIBA                        1198
#define IDC_HIBB                        1199
#define IDC_HIBC                        1200
#define IDC_HIBD                        1201
#define IDC_HIBE                        1202
#define IDC_HIBF                        1203
#define IDC_BBF                         1204
#define IDC_BBE                         1205
#define IDC_BBD                         1206
#define IDC_BBC                         1207
#define IDC_BBB                         1208
#define IDC_BBA                         1209
#define IDC_BB9                         1210
#define IDC_BB8                         1211
#define IDC_BB7                         1212
#define IDC_BB6                         1213
#define IDC_BB5                         1214
#define IDC_BB0                         1215
#define IDC_BB1                         1216
#define IDC_BB2                         1217
#define IDC_BB3                         1218
#define IDC_BB4                         1219
#define IDC_LOB0                        1220
#define IDC_LOB1                        1221
#define IDC_LOB2                        1222
#define IDC_LOB3                        1223
#define IDC_LOB4                        1224
#define IDC_LOB5                        1225
#define IDC_LOB6                        1226
#define IDC_LOB7                        1227
#define IDC_LOB8                        1228
#define IDC_LOB9                        1229
#define IDC_LOBA                        1230
#define IDC_LOBB                        1231
#define IDC_LOBC                        1232
#define IDC_LOBD                        1233
#define IDC_LOBE                        1234
#define IDC_LOBF                        1235
#define IDC_TSB1                        1236
#define IDC_TSB2                        1237
#define IDC_TSB3                        1238
#define IDC_AND3                        1239
#define IDC_HIC0                        1240
#define IDC_HIC1                        1241
#define IDC_HIC2                        1242
#define IDC_HIC3                        1243
#define IDC_HIC4                        1244
#define IDC_HIC5                        1245
#define IDC_HIC6                        1246
#define IDC_HIC7                        1247
#define IDC_HIC8                        1248
#define IDC_HIC9                        1249
#define IDC_HICA                        1250
#define IDC_HICB                        1251
#define IDC_HICC                        1252
#define IDC_HICD                        1253
#define IDC_HICE                        1254
#define IDC_HICF                        1255
#define IDC_CBF                         1256
#define IDC_CBE                         1257
#define IDC_CBD                         1258
#define IDC_CBC                         1259
#define IDC_CBB                         1260
#define IDC_CBA                         1261
#define IDC_CB9                         1262
#define IDC_CB8                         1263
#define IDC_CB7                         1264
#define IDC_CB6                         1265
#define IDC_CB5                         1266
#define IDC_CB0                         1267
#define IDC_CB1                         1268
#define IDC_CB2                         1269
#define IDC_CB3                         1270
#define IDC_CB4                         1271
#define IDC_LOC0                        1272
#define IDC_LOC1                        1273
#define IDC_LOC2                        1274
#define IDC_LOC3                        1275
#define IDC_LOC4                        1276
#define IDC_LOC5                        1277
#define IDC_LOC6                        1278
#define IDC_LOC7                        1279
#define IDC_LOC8                        1280
#define IDC_LOC9                        1281
#define IDC_LOCA                        1282
#define IDC_LOCB                        1283
#define IDC_LOCC                        1284
#define IDC_LOCD                        1285
#define IDC_LOCE                        1286
#define IDC_LOCF                        1287
#define IDC_TSC1                        1288
#define IDC_TSC2                        1289
#define IDC_TSC3                        1290
#define IDC_KEY_START                   1291
#define IDC_TRIDLE                      1292
#define IDC_TST7                        1293
#define IDC_TSTN                        1294
#define IDC_TST8                        1295
#define IDC_GATE0                       1298
#define IDC_GATE1                       1299
#define IDC_SFREE                       1300
#define IDC_TRNUM                       1301
#define IDC_FILE                        1302
#define IDC_INFO                        1303
#define IDC_MAP                         1304
#define IDC_PATCODE                     1305
#define IDC_PATSEX                      1306
#define IDC_PATBIRTH                    1307
#define IDC_PATNAME                     1308
#define IDC_DATETIME                    1310
#define IDC_EQUIPCODE                   1311
#define IDC_STRNUM                      1311
#define IDC_EQUIPMENT                   1311
#define IDC_INVCODE                     1312
#define IDC_LIST                        1312
#define IDC_RESPINVCODE                 1313
#define IDC_RESPCODE                    1313
#define IDC_RESEARCHER                  1313
#define IDC_INVCODE2                    1314
#define IDC_STIMCODE                    1314
#define IDC_BFOLDER                     1316
#define IDC_EFOLDER                     1317
#define IDC_BEXP                        1318
#define IDC_BSUBJ                       1319
#define IDC_PLUS                        1320
#define IDC_PBDAY                       1321
#define IDC_SPBDAY                      1322
#define IDC_PBMONTH                     1323
#define IDC_PBYEAR                      1324
#define IDC_SPBDAY2                     1325
#define IDC_SPBYEAR                     1325
#define IDC_MAINTIMER                   1325
#define IDC_BPSTATIC                    1326
#define IDC_TEXT                        1327
#define IDC_TRIAL                       1328
#define IDC_TEXT2                       1329
#define IDC_LINK                        1330
#define IDC_PREVIOUS                    1331
#define ID_POWER_PANE                   1500
#define ID_BAT_PANE                     1501
#define ID_CMS_PANE                     1502
#define ID_ONE                          32772
#define ID_TWO                          32773
#define ID_BUTTON32774                  32774
#define ID_WINDOW_TILE                  32776
#define ID_RUN_GO                       32777
#define ID_RUN_TEST                     32779
#define ID_TOOLS_SETTINS                32781
#define ID_OSC_NEW                      32782
#define ID_WINDOW_DOCKALL               32791
#define ID_TOOLS_LOADELECTRODENAMES     32792
#define ID_RUN_PAUSE                    32793
#define ID_RUN_WRDISABLE                32795
#define ID_RUN_WRMANUAL                 32796
#define ID_SNAP_NEW                     32798
#define ID_MATEXP                       32800
#define ID_EXPORT_MATLAB                32800
#define ID_FILE_OPENCONFIG              32804
#define ID_FILE_SAVECONFIG              32805
#define ID_HELP_ACTDHELP                32808

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NO_MFC                     1
#define _APS_NEXT_RESOURCE_VALUE        228
#define _APS_NEXT_COMMAND_VALUE         32812
#define _APS_NEXT_CONTROL_VALUE         1332
#define _APS_NEXT_SYMED_VALUE           102
#endif
#endif
